export const cinemaList = [
    { id: 10, name: "UGC Ciné Cité Les Halles" },
    { id: 53, name: "UGC Grand Normandie" },
    { id: 2, name: "UGC Normandie" },
    { id: 7, name: "UGC Ciné Cité Maillot" },
    { id: 14, name: "UGC Montparnasse" },
    { id: 15, name: "UGC Rotonde" },
    { id: 13, name: "UGC Odéon" },
    { id: 4, name: "UGC Danton" },
    { id: 12, name: "UGC Ciné Cité Bercy" },
    { id: 11, name: "UGC Lyon Bastille" },
    { id: 5, name: "UGC Gobelins" },
    { id: 9, name: "UGC Opéra" },
    { id: 37, name: "UGC Ciné Cité Paris 19" },
    { id: 20, name: "UGC Ciné Cité La Défense " },
    { id: 59, name: "UGC Issy-les-Moulineaux" },
    { id: 18, name: "UGC Ciné Cité Rosny" },
    { id: 38, name: "UGC Ciné Cité O Parinor " },
    { id: 21, name: "UGC Ciné Cité Créteil" },
    { id: 19, name: "UGC Ciné Cité Noisy-le-Grand" },
    { id: 16, name: "UGC Ciné Cité Cergy-le-Haut" },
    { id: 17, name: "UGC Enghien" },
    { id: 43, name: "UGC Ciné Cité Vélizy" },
    { id: 44, name: "UGC Ciné Cité Parly" },
    { id: 6, name: "UGC Ciné Cité SQY Ouest" },
    { id: 40, name: "UGC Roxane Versailles" },
    { id: 41, name: "UGC Cyrano Versailles" },
    { id: 23, name: "UGC Les Ulis" },
    { id: 55, name: "UGC Plaisir" },
    { id: 47, name: "Le Central" },
    { id: 48, name: "C2L Saint Germain" },
    { id: 49, name: "Le Cin’Hoche Sartrouville" },
    { id: 54, name: "C2L Poissy" },
    { id: 39, name: "UGC Majestic" },
    { id: 1, name: "UGC Ciné Cité Bordeaux Gambetta" },
    { id: 57, name: "UGC Ciné Cité Bassins à Flot" },
    { id: 42, name: "UGC Talence" },
    { id: 27, name: "UGC Ciné Cité Mondeville" },
    { id: 25, name: "UGC Ciné Cité Lille" },
    { id: 24, name: "UGC Ciné Cité Villeneuve d'Ascq" },
    { id: 45, name: "Le Métropole" },
    { id: 46, name: "Le Majestic" },
    { id: 51, name: "Le Duplexe" },
    { id: 52, name: "Les Écrans" },
    { id: 32, name: "UGC Ciné Cité Internationale" },
    { id: 36, name: "UGC Ciné Cité Confluence" },
    { id: 33, name: "UGC Astoria" },
    { id: 58, name: "UGC Ciné Cité Part-Dieu" },
    { id: 28, name: "UGC Nancy Saint Jean" },
    { id: 29, name: "UGC Ciné Cité Ludres" },
    { id: 31, name: "UGC Ciné Cité Atlantis" },
    { id: 30, name: "UGC Ciné Cité Strasbourg" },
    { id: 56, name: "UGC Montaudran" },
] as const;